version: '3'

services:
  d3-iroha:
    image: hyperledger/iroha:develop
    container_name: d3-iroha
    ports:
      - 50051:50051
      - 10001:10001
    depends_on:
      - d3-iroha-postgres
    tty: true
    environment:
      - KEY=keys/node0
    entrypoint:
      - /opt/iroha_data/entrypoint.sh
    volumes:
      - iroha_block_store:/tmp/block_store
      - ./iroha:/opt/iroha_data

  d3-iroha-postgres:
    image: postgres:9.5
    container_name: d3-iroha-postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data

  d3-eth-relay:
    image: nexus.iroha.tech:19002/d3-deploy/eth-relay:${PROFILE}
    container_name: d3-eth-relay
    depends_on:
      - d3-iroha
    volumes:
      - ./:/opt/notary/deploy
    environment:
      - ETH_CREDENTIALS_PASSWORD
      - ETH_NODE_LOGIN
      - ETH_NODE_PASSWORD


  d3-registration:
    image: nexus.iroha.tech:19002/d3-deploy/registration:${PROFILE}
    container_name: d3-registration
    depends_on:
      - d3-iroha
     # - d3-eth-node0
    ports:
      - 8083:8083
    volumes:
      - ./:/opt/notary/deploy



  d3-notary:
    image: nexus.iroha.tech:19002/d3-deploy/notary:${PROFILE}
    container_name: d3-notary
    depends_on:
      - d3-iroha
    ports:
      - 8080:8080
    volumes:
      - ./:/opt/notary/deploy
    environment:
      - ETH_CREDENTIALS_PASSWORD
      - ETH_NODE_LOGIN
      - ETH_NODE_PASSWORD


  d3-withdrawal:
    image: nexus.iroha.tech:19002/d3-deploy/withdrawal:${PROFILE}
    container_name: d3-withdrawal
    depends_on:
      - d3-iroha
    volumes:
      - ./:/opt/notary/deploy
    environment:
      - ETH_CREDENTIALS_PASSWORD
      - ETH_NODE_LOGIN
      - ETH_NODE_PASSWORDsou

  grpcwebproxy:
    image: nexus.iroha.tech:19002/d3-deploy/grpcwebproxy
    container_name: d3-grpcwebproxy
    depends_on:
      - d3-iroha
    ports:
      - 8081:8080
      - 8443:8443
    entrypoint:
      - grpcwebproxy
      - --backend_addr=d3-iroha:50051
      - --run_tls_server=false

volumes:
  iroha_block_store:
