version: '3'

services:
  d3-iroha:
    image: hyperledger/iroha:develop
    container_name: d3ledger-iroha
    ports:
      - 50051:50051
    depends_on:
      - d3-iroha-postgres
    tty: true
    environment:
      - KEY=keys/node0
    entrypoint:
      - /opt/iroha_data/entrypoint.sh
    volumes:
      - iroha_block_store:/tmp/block_store
      - ./iroha:/opt/iroha_data

  d3-iroha-postgres:
    image: postgres:9.5
    container_name: d3ledger-postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data

  # ethereum
  d3-eth-node0:
    build:
      context: .
      dockerfile: ethereum/parity.dockerfile
    container_name: d3-eth-node0
    volumes:
      - ./ethereum:/eth
    environment:
      - NODE=0
    ports:
      - 8545:8545

  d3-eth-node1:
    build:
      context: .
      dockerfile: ethereum/parity.dockerfile
    container_name: d3-eth-node1
    volumes:
      - ./ethereum:/eth
    environment:
      - NODE=1

  d3-eth-manager:
    build:
      context: .
      dockerfile: ethereum/eth-manager.dockerfile
    container_name: d3-eth-manager
    depends_on:
      - d3-eth-node0
      - d3-eth-node1
    volumes:
      - ./ethereum:/eth

  # d3
  d3-notary-postgres:
    image: postgres:9.5
    container_name: d3-notary-postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./db/sql/init:/docker-entrypoint-initdb.d
      - /var/lib/postgresql/data
    ports:
      - 5432:5432

  d3-notary:
    build:
      context: .
      dockerfile: notary.dockerfile
    container_name: d3-notary
    depends_on:
      - d3-notary-postgres
    ports:
      - 8083:8083

volumes:
  iroha_block_store:
